#define LOADING_SCENE	1
#define MENU_SCENE	2
#define PLAY_SCENE	3
#define SELECT_THEME_SCENE 4

#define EFFECT_DURATION 0.18
#define NUM_MODE	5
#define TAG			"GPIKACHU"
#define DRAG_DISTANCE 30

#define MOVE_EFFECT_TIME  0.03125f
#define SPAWN_EFFECT_TIME  0.0625f
#define MERGE_EFFECT_TIME  0.0625f

#define LAYER_DIALOG 1000
#define LAYER_PLAY 100
#define CONGRAT_NUM 2048
